#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

require 'ruby_php_serialization/tokenizer'

module RubyPhpSerialization
  class Parser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 58)
  
	def parse(string)
		@tokenizer = Tokenizer.new(string)
		do_parse
		return @object
	ensure
		@tokenizer = nil
	end
  
  def next_token
    @tokenizer.next_token
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    29,     7,    24,    34,    18,     7,    19,    34,     2,     3,
    20,    30,     7,     9,     2,     3,     1,    21,     7,     9,
     2,     3,     1,    22,     7,     9,    23,    17,     1,    25,
    16,    15,    36,    37,    38,    14,    40,    13,    42,    43 ]

racc_action_check = [
    27,    29,    19,    29,     9,    27,    13,    27,    36,    36,
    14,    27,    36,    36,    38,    38,    36,    15,    38,    38,
     0,     0,    38,    17,     0,     0,    18,     7,     0,    24,
     5,     4,    32,    34,    35,     3,    37,     1,    40,    42 ]

racc_action_pointer = [
    17,    32,   nil,    30,    31,    28,   nil,    22,   nil,    -1,
   nil,   nil,   nil,     0,     4,    17,   nil,    17,    20,    -3,
   nil,   nil,   nil,   nil,    17,   nil,   nil,    -2,   nil,    -6,
   nil,   nil,    30,   nil,    28,    32,     5,    30,    11,   nil,
    33,   nil,    29,   nil ]

racc_action_default = [
   -20,   -20,    -7,   -20,   -20,   -20,    -2,   -20,    -3,   -20,
    -4,    -5,    -6,   -20,   -20,   -20,    -1,   -20,   -20,   -20,
    -8,    44,    -9,   -10,   -20,   -12,   -15,   -20,   -19,   -20,
   -13,   -14,   -20,   -18,   -20,   -20,   -20,   -20,   -20,   -16,
   -20,   -17,   -20,   -11 ]

racc_goto_table = [
     5,    32,    33,    35,    33,    27,    26,    31,     4,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    39,   nil,    41 ]

racc_goto_check = [
     2,    12,     5,    12,     5,     9,    10,    11,     1,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,     2 ]

racc_goto_pointer = [
   nil,     8,     0,   nil,   nil,   -25,   nil,   nil,   nil,   -21,
   -19,   -20,   -26 ]

racc_goto_default = [
   nil,   nil,   nil,     6,     8,    10,    11,    12,    28,   nil,
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  2, 15, :_reduce_1,
  1, 16, :_reduce_2,
  1, 16, :_reduce_3,
  1, 16, :_reduce_4,
  1, 16, :_reduce_5,
  1, 16, :_reduce_6,
  1, 17, :_reduce_7,
  3, 18, :_reduce_8,
  3, 19, :_reduce_9,
  3, 20, :_reduce_10,
  5, 22, :_reduce_11,
  0, 24, :_reduce_12,
  8, 21, :_reduce_13,
  2, 23, :_reduce_14,
  0, 23, :_reduce_15,
  3, 25, :_reduce_16,
  4, 25, :_reduce_17,
  1, 26, :_reduce_18,
  1, 26, :_reduce_19 ]

racc_reduce_n = 20

racc_shift_n = 44

racc_token_table = {
  false => 0,
  :error => 1,
  ";" => 2,
  "N" => 3,
  "b" => 4,
  ":" => 5,
  :NUMBER => 6,
  "i" => 7,
  "d" => 8,
  "s" => 9,
  :STRING => 10,
  "a" => 11,
  "{" => 12,
  "}" => 13 }

racc_nt_base = 14

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\";\"",
  "\"N\"",
  "\"b\"",
  "\":\"",
  "NUMBER",
  "\"i\"",
  "\"d\"",
  "\"s\"",
  "STRING",
  "\"a\"",
  "\"{\"",
  "\"}\"",
  "$start",
  "serialization",
  "object",
  "null",
  "bool",
  "integer",
  "double",
  "array",
  "string",
  "array_items",
  "@1",
  "array_item",
  "array_key" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parser.y', 3)
  def _reduce_1(val, _values, result)
     @object = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 6)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 7)
  def _reduce_3(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 8)
  def _reduce_4(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 9)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 10)
  def _reduce_6(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 13)
  def _reduce_7(val, _values, result)
     result = nil 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 16)
  def _reduce_8(val, _values, result)
     result = Integer(val[2]) > 0 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_9(val, _values, result)
     result = Integer(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 22)
  def _reduce_10(val, _values, result)
     result = Float(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_11(val, _values, result)
     result = val[4] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_12(val, _values, result)
     @numeric_array = true 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_13(val, _values, result)
    									if @numeric_array
										result = []
										val[6].each { |(i,v)| result[i] = v }
									else
										result = Hash[*val[6].flatten]
									end
								
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_14(val, _values, result)
     result = val[0] << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_15(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_16(val, _values, result)
     result = [val[0], val[2]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_17(val, _values, result)
     result = [val[1], val[3]] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_18(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_19(val, _values, result)
     @numeric_array = false; result = val[0] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module RubyPhpSerialization
